const korpus_mock_data = [
    {
        id: 1,
        title: 'Til korpusi nima?',
        description: 'Korpus (lotincha “tana” demakdir) elektron holda saqlanadigan til birliklari majmuasi bo‘lib, tilshunoslar uchun turli muammolarni hal etish manbasi, foydalanuvchilar uchun esa lingvodidaktik va ta’limiy ahamiyatga ega tizimdir. Korpus tilshunosligi kompyuter lingvistikasi zamirida shakllangan soha bo‘lib, uning obyekti tabiiy tildagi matnlar, predmeti esa til korpuslari hisoblanadi. Muayyan tilning deyarli barcha tipdagi matnlari bazasidan iborat, turli maqsadlar doirasida lingvistik izohlari bilan qayta ishlangan korpus turi Milliy til korpusi, muayyan maqsadga mo‘ljallangan maxsus korpuslar esa uning xususiy / tarkibiy turi hisoblanadi. Jumladan, aksentologik korpus, parallel korpus, mualliflik korpusi, gazetalar korpusi, ta’limiy korpus, badiiy matnlar korpusi va h.k.\n' +
            '\n' +
            'Mualliflik korpusi muayyan bir muallif qalamiga mansub matnlar majmuasidan iborat tizim bo‘lib, asosan, yozuvchining yozish uslubi, asarlaridagi til, matn xususiyatlarini axborot texnologiyalari yordamida semantik tasniflab, tadqiq etishga asoslangan elektron shakdagi ma’lumotlar bazasi sanaladi. Mualliflik korpusining boshqa korpuslardan farqi uning bazasida muayyan bir muallif asarlari jamlanadi, matnlar qayta ishlanadi, grammatik va semantik teglanadi, qidiruv tizimi orqali muallifga tegishli materiallardan zaruriy ma’lumotlar, lingvistik ifodalar aniqlanadi, matnlar asosida statistik ma’lumotlar taqdim etiladi, metama’lumotlar aniq beriladi. Shunday qilib mualliflik korpusi keng imkoniyatli qidiruv tizimiga ega bo‘lib, muallif ijod qilgan barcha tur va janrdagi asarlar qamrab olinadigan, maxsus parametrlar asosida ham qidiruv imkoniyatiga ega, hajmi chegaralanmagan, muallif va uning ijodi bilan bog‘liq manbalarni qulay va tezkor olish mumkin bo‘lgan elektron ma’lumotlar bazasi hisoblanadi.'
    },
    {
        id: 2,
        title: 'Korpus turlari',
        description: 'Korpus(lotincha “tana” demakdir) elektron holda saqlanadigan til birliklari majmuasi bo‘lib, tilshunoslar uchun turli muammolarni hal etish manbasi, foydalanuvchilar uchun esa lingvodidaktik va ta’limiy ahamiyatga ega tizimdir. Korpus tilshunosligi kompyuter lingvistikasi zamirida shakllangan soha bo‘lib, uning obyekti tabiiy tildagi matnlar, predmeti esa til korpuslari hisoblanadi. Muayyan tilning deyarli barcha tipdagi matnlari bazasidan iborat, turli maqsadlar doirasida lingvistik izohlari bilan qayta ishlangan korpus turi Milliy til korpusi, muayyan maqsadga mo‘ljallangan maxsus korpuslar esa uning xususiy / tarkibiy turi hisoblanadi. Jumladan, aksentologik korpus, parallel korpus, mualliflik korpusi, gazetalar korpusi, ta’limiy korpus, badiiy matnlar korpusi va h.k.\n' +
            '\n' +
            'Mualliflik korpusi muayyan bir muallif qalamiga mansub matnlar majmuasidan iborat tizim bo‘lib, asosan, yozuvchining yozish uslubi, asarlaridagi til, matn xususiyatlarini axborot texnologiyalari yordamida semantik tasniflab, tadqiq etishga asoslangan elektron shakdagi ma’lumotlar bazasi sanaladi. Mualliflik korpusining boshqa korpuslardan farqi uning bazasida muayyan bir muallif asarlari jamlanadi, matnlar qayta ishlanadi, grammatik va semantik teglanadi, qidiruv tizimi orqali muallifga tegishli materiallardan zaruriy ma’lumotlar, lingvistik ifodalar aniqlanadi, matnlar asosida statistik ma’lumotlar taqdim etiladi, metama’lumotlar aniq beriladi. Shunday qilib mualliflik korpusi keng imkoniyatli qidiruv tizimiga ega bo‘lib, muallif ijod qilgan barcha tur va janrdagi asarlar qamrab olinadigan, maxsus parametrlar asosida ham qidiruv imkoniyatiga ega, hajmi chegaralanmagan, muallif va uning ijodi bilan bog‘liq manbalarni qulay va tezkor olish mumkin bo‘lgan elektron ma’lumotlar bazasi hisoblanadi.'
    },
    {
        id: 3,
        title: 'Korpus yaratish jarayoni',
        description: 'Korpus (lotincha “tana” demakdir) elektron holda saqlanadigan til birliklari majmuasi bo‘lib, tilshunoslar uchun turli muammolarni hal etish manbasi, foydalanuvchilar uchun esa lingvodidaktik va ta’limiy ahamiyatga ega tizimdir. Korpus tilshunosligi kompyuter lingvistikasi zamirida shakllangan soha bo‘lib, uning obyekti tabiiy tildagi matnlar, predmeti esa til korpuslari hisoblanadi. Muayyan tilning deyarli barcha tipdagi matnlari bazasidan iborat, turli maqsadlar doirasida lingvistik izohlari bilan qayta ishlangan korpus turi Milliy til korpusi, muayyan maqsadga mo‘ljallangan maxsus korpuslar esa uning xususiy / tarkibiy turi hisoblanadi. Jumladan, aksentologik korpus, parallel korpus, mualliflik korpusi, gazetalar korpusi, ta’limiy korpus, badiiy matnlar korpusi va h.k.\n' +
            '\n' +
            'Mualliflik korpusi muayyan bir muallif qalamiga mansub matnlar majmuasidan iborat tizim bo‘lib, asosan, yozuvchining yozish uslubi, asarlaridagi til, matn xususiyatlarini axborot texnologiyalari yordamida semantik tasniflab, tadqiq etishga asoslangan elektron shakdagi ma’lumotlar bazasi sanaladi. Mualliflik korpusining boshqa korpuslardan farqi uning bazasida muayyan bir muallif asarlari jamlanadi, matnlar qayta ishlanadi, grammatik va semantik teglanadi, qidiruv tizimi orqali muallifga tegishli materiallardan zaruriy ma’lumotlar, lingvistik ifodalar aniqlanadi, matnlar asosida statistik ma’lumotlar taqdim etiladi, metama’lumotlar aniq beriladi. Shunday qilib mualliflik korpusi keng imkoniyatli qidiruv tizimiga ega bo‘lib, muallif ijod qilgan barcha tur va janrdagi asarlar qamrab olinadigan, maxsus parametrlar asosida ham qidiruv imkoniyatiga ega, hajmi chegaralanmagan, muallif va uning ijodi bilan bog‘liq manbalarni qulay va tezkor olish mumkin bo‘lgan elektron ma’lumotlar bazasi hisoblanadi.'
    },
    {
        id: 4,
        title: 'Korpusdan foydalanish',
        description: 'Korpus (lotincha “tana” demakdir) elektron holda saqlanadigan til birliklari majmuasi bo‘lib, tilshunoslar uchun turli muammolarni hal etish manbasi, foydalanuvchilar uchun esa lingvodidaktik va ta’limiy ahamiyatga ega tizimdir. Korpus tilshunosligi kompyuter lingvistikasi zamirida shakllangan soha bo‘lib, uning obyekti tabiiy tildagi matnlar, predmeti esa til korpuslari hisoblanadi. Muayyan tilning deyarli barcha tipdagi matnlari bazasidan iborat, turli maqsadlar doirasida lingvistik izohlari bilan qayta ishlangan korpus turi Milliy til korpusi, muayyan maqsadga mo‘ljallangan maxsus korpuslar esa uning xususiy / tarkibiy turi hisoblanadi. Jumladan, aksentologik korpus, parallel korpus, mualliflik korpusi, gazetalar korpusi, ta’limiy korpus, badiiy matnlar korpusi va h.k.\n' +
            '\n' +
            'Mualliflik korpusi muayyan bir muallif qalamiga mansub matnlar majmuasidan iborat tizim bo‘lib, asosan, yozuvchining yozish uslubi, asarlaridagi til, matn xususiyatlarini axborot texnologiyalari yordamida semantik tasniflab, tadqiq etishga asoslangan elektron shakdagi ma’lumotlar bazasi sanaladi. Mualliflik korpusining boshqa korpuslardan farqi uning bazasida muayyan bir muallif asarlari jamlanadi, matnlar qayta ishlanadi, grammatik va semantik teglanadi, qidiruv tizimi orqali muallifga tegishli materiallardan zaruriy ma’lumotlar, lingvistik ifodalar aniqlanadi, matnlar asosida statistik ma’lumotlar taqdim etiladi, metama’lumotlar aniq beriladi. Shunday qilib mualliflik korpusi keng imkoniyatli qidiruv tizimiga ega bo‘lib, muallif ijod qilgan barcha tur va janrdagi asarlar qamrab olinadigan, maxsus parametrlar asosida ham qidiruv imkoniyatiga ega, hajmi chegaralanmagan, muallif va uning ijodi bilan bog‘liq manbalarni qulay va tezkor olish mumkin bo‘lgan elektron ma’lumotlar bazasi hisoblanadi.'
    },
    {
        id: 5,
        title: 'Korpusning afzalliklari',
        description: 'Korpus (lotincha “tana” demakdir) elektron holda saqlanadigan til birliklari majmuasi bo‘lib, tilshunoslar uchun turli muammolarni hal etish manbasi, foydalanuvchilar uchun esa lingvodidaktik va ta’limiy ahamiyatga ega tizimdir. Korpus tilshunosligi kompyuter lingvistikasi zamirida shakllangan soha bo‘lib, uning obyekti tabiiy tildagi matnlar, predmeti esa til korpuslari hisoblanadi. Muayyan tilning deyarli barcha tipdagi matnlari bazasidan iborat, turli maqsadlar doirasida lingvistik izohlari bilan qayta ishlangan korpus turi Milliy til korpusi, muayyan maqsadga mo‘ljallangan maxsus korpuslar esa uning xususiy / tarkibiy turi hisoblanadi. Jumladan, aksentologik korpus, parallel korpus, mualliflik korpusi, gazetalar korpusi, ta’limiy korpus, badiiy matnlar korpusi va h.k.\n' +
            '\n' +
            'Mualliflik korpusi muayyan bir muallif qalamiga mansub matnlar majmuasidan iborat tizim bo‘lib, asosan, yozuvchining yozish uslubi, asarlaridagi til, matn xususiyatlarini axborot texnologiyalari yordamida semantik tasniflab, tadqiq etishga asoslangan elektron shakdagi ma’lumotlar bazasi sanaladi. Mualliflik korpusining boshqa korpuslardan farqi uning bazasida muayyan bir muallif asarlari jamlanadi, matnlar qayta ishlanadi, grammatik va semantik teglanadi, qidiruv tizimi orqali muallifga tegishli materiallardan zaruriy ma’lumotlar, lingvistik ifodalar aniqlanadi, matnlar asosida statistik ma’lumotlar taqdim etiladi, metama’lumotlar aniq beriladi. Shunday qilib mualliflik korpusi keng imkoniyatli qidiruv tizimiga ega bo‘lib, muallif ijod qilgan barcha tur va janrdagi asarlar qamrab olinadigan, maxsus parametrlar asosida ham qidiruv imkoniyatiga ega, hajmi chegaralanmagan, muallif va uning ijodi bilan bog‘liq manbalarni qulay va tezkor olish mumkin bo‘lgan elektron ma’lumotlar bazasi hisoblanadi.'
    },
    {
        id: 6,
        title: 'Korpus va tilshunoslik',
        description: 'Korpus (lotincha “tana” demakdir) elektron holda saqlanadigan til birliklari majmuasi bo‘lib, tilshunoslar uchun turli muammolarni hal etish manbasi, foydalanuvchilar uchun esa lingvodidaktik va ta’limiy ahamiyatga ega tizimdir. Korpus tilshunosligi kompyuter lingvistikasi zamirida shakllangan soha bo‘lib, uning obyekti tabiiy tildagi matnlar, predmeti esa til korpuslari hisoblanadi. Muayyan tilning deyarli barcha tipdagi matnlari bazasidan iborat, turli maqsadlar doirasida lingvistik izohlari bilan qayta ishlangan korpus turi Milliy til korpusi, muayyan maqsadga mo‘ljallangan maxsus korpuslar esa uning xususiy / tarkibiy turi hisoblanadi. Jumladan, aksentologik korpus, parallel korpus, mualliflik korpusi, gazetalar korpusi, ta’limiy korpus, badiiy matnlar korpusi va h.k.\n' +
            '\n' +
            'Mualliflik korpusi muayyan bir muallif qalamiga mansub matnlar majmuasidan iborat tizim bo‘lib, asosan, yozuvchining yozish uslubi, asarlaridagi til, matn xususiyatlarini axborot texnologiyalari yordamida semantik tasniflab, tadqiq etishga asoslangan elektron shakdagi ma’lumotlar bazasi sanaladi. Mualliflik korpusining boshqa korpuslardan farqi uning bazasida muayyan bir muallif asarlari jamlanadi, matnlar qayta ishlanadi, grammatik va semantik teglanadi, qidiruv tizimi orqali muallifga tegishli materiallardan zaruriy ma’lumotlar, lingvistik ifodalar aniqlanadi, matnlar asosida statistik ma’lumotlar taqdim etiladi, metama’lumotlar aniq beriladi. Shunday qilib mualliflik korpusi keng imkoniyatli qidiruv tizimiga ega bo‘lib, muallif ijod qilgan barcha tur va janrdagi asarlar qamrab olinadigan, maxsus parametrlar asosida ham qidiruv imkoniyatiga ega, hajmi chegaralanmagan, muallif va uning ijodi bilan bog‘liq manbalarni qulay va tezkor olish mumkin bo‘lgan elektron ma’lumotlar bazasi hisoblanadi.'
    },
    {
        id: 7,
        title: 'Korpusning kelajagi',
        description: 'Korpus (lotincha “tana” demakdir) elektron holda saqlanadigan til birliklari majmuasi bo‘lib, tilshunoslar uchun turli muammolarni hal etish manbasi, foydalanuvchilar uchun esa lingvodidaktik va ta’limiy ahamiyatga ega tizimdir. Korpus tilshunosligi kompyuter lingvistikasi zamirida shakllangan soha bo‘lib, uning obyekti tabiiy tildagi matnlar, predmeti esa til korpuslari hisoblanadi. Muayyan tilning deyarli barcha tipdagi matnlari bazasidan iborat, turli maqsadlar doirasida lingvistik izohlari bilan qayta ishlangan korpus turi Milliy til korpusi, muayyan maqsadga mo‘ljallangan maxsus korpuslar esa uning xususiy / tarkibiy turi hisoblanadi. Jumladan, aksentologik korpus, parallel korpus, mualliflik korpusi, gazetalar korpusi, ta’limiy korpus, badiiy matnlar korpusi va h.k.\n' +
            '\n' +
            'Mualliflik korpusi muayyan bir muallif qalamiga mansub matnlar majmuasidan iborat tizim bo‘lib, asosan, yozuvchining yozish uslubi, asarlaridagi til, matn xususiyatlarini axborot texnologiyalari yordamida semantik tasniflab, tadqiq etishga asoslangan elektron shakdagi ma’lumotlar bazasi sanaladi. Mualliflik korpusining boshqa korpuslardan farqi uning bazasida muayyan bir muallif asarlari jamlanadi, matnlar qayta ishlanadi, grammatik va semantik teglanadi, qidiruv tizimi orqali muallifga tegishli materiallardan zaruriy ma’lumotlar, lingvistik ifodalar aniqlanadi, matnlar asosida statistik ma’lumotlar taqdim etiladi, metama’lumotlar aniq beriladi. Shunday qilib mualliflik korpusi keng imkoniyatli qidiruv tizimiga ega bo‘lib, muallif ijod qilgan barcha tur va janrdagi asarlar qamrab olinadigan, maxsus parametrlar asosida ham qidiruv imkoniyatiga ega, hajmi chegaralanmagan, muallif va uning ijodi bilan bog‘liq manbalarni qulay va tezkor olish mumkin bo‘lgan elektron ma’lumotlar bazasi hisoblanadi.'
    },
    {
        id: 8,
        title: 'Korpus va sun’iy intellekt',
        description: 'Korpus (lotincha “tana” demakdir) elektron holda saqlanadigan til birliklari majmuasi bo‘lib, tilshunoslar uchun turli muammolarni hal etish manbasi, foydalanuvchilar uchun esa lingvodidaktik va ta’limiy ahamiyatga ega tizimdir. Korpus tilshunosligi kompyuter lingvistikasi zamirida shakllangan soha bo‘lib, uning obyekti tabiiy tildagi matnlar, predmeti esa til korpuslari hisoblanadi. Muayyan tilning deyarli barcha tipdagi matnlari bazasidan iborat, turli maqsadlar doirasida lingvistik izohlari bilan qayta ishlangan korpus turi Milliy til korpusi, muayyan maqsadga mo‘ljallangan maxsus korpuslar esa uning xususiy / tarkibiy turi hisoblanadi. Jumladan, aksentologik korpus, parallel korpus, mualliflik korpusi, gazetalar korpusi, ta’limiy korpus, badiiy matnlar korpusi va h.k.\n' +
            '\n' +
            'Mualliflik korpusi muayyan bir muallif qalamiga mansub matnlar majmuasidan iborat tizim bo‘lib, asosan, yozuvchining yozish uslubi, asarlaridagi til, matn xususiyatlarini axborot texnologiyalari yordamida semantik tasniflab, tadqiq etishga asoslangan elektron shakdagi ma’lumotlar bazasi sanaladi. Mualliflik korpusining boshqa korpuslardan farqi uning bazasida muayyan bir muallif asarlari jamlanadi, matnlar qayta ishlanadi, grammatik va semantik teglanadi, qidiruv tizimi orqali muallifga tegishli materiallardan zaruriy ma’lumotlar, lingvistik ifodalar aniqlanadi, matnlar asosida statistik ma’lumotlar taqdim etiladi, metama’lumotlar aniq beriladi. Shunday qilib mualliflik korpusi keng imkoniyatli qidiruv tizimiga ega bo‘lib, muallif ijod qilgan barcha tur va janrdagi asarlar qamrab olinadigan, maxsus parametrlar asosida ham qidiruv imkoniyatiga ega, hajmi chegaralanmagan, muallif va uning ijodi bilan bog‘liq manbalarni qulay va tezkor olish mumkin bo‘lgan elektron ma’lumotlar bazasi hisoblanadi.'
    },
    {
        id: 9,
        title: 'Korpusning to‘g‘ri tuzilishi',
        description: 'Korpus (lotincha “tana” demakdir) elektron holda saqlanadigan til birliklari majmuasi bo‘lib, tilshunoslar uchun turli muammolarni hal etish manbasi, foydalanuvchilar uchun esa lingvodidaktik va ta’limiy ahamiyatga ega tizimdir. Korpus tilshunosligi kompyuter lingvistikasi zamirida shakllangan soha bo‘lib, uning obyekti tabiiy tildagi matnlar, predmeti esa til korpuslari hisoblanadi. Muayyan tilning deyarli barcha tipdagi matnlari bazasidan iborat, turli maqsadlar doirasida lingvistik izohlari bilan qayta ishlangan korpus turi Milliy til korpusi, muayyan maqsadga mo‘ljallangan maxsus korpuslar esa uning xususiy / tarkibiy turi hisoblanadi. Jumladan, aksentologik korpus, parallel korpus, mualliflik korpusi, gazetalar korpusi, ta’limiy korpus, badiiy matnlar korpusi va h.k.\n' +
            '\n' +
            'Mualliflik korpusi muayyan bir muallif qalamiga mansub matnlar majmuasidan iborat tizim bo‘lib, asosan, yozuvchining yozish uslubi, asarlaridagi til, matn xususiyatlarini axborot texnologiyalari yordamida semantik tasniflab, tadqiq etishga asoslangan elektron shakdagi ma’lumotlar bazasi sanaladi. Mualliflik korpusining boshqa korpuslardan farqi uning bazasida muayyan bir muallif asarlari jamlanadi, matnlar qayta ishlanadi, grammatik va semantik teglanadi, qidiruv tizimi orqali muallifga tegishli materiallardan zaruriy ma’lumotlar, lingvistik ifodalar aniqlanadi, matnlar asosida statistik ma’lumotlar taqdim etiladi, metama’lumotlar aniq beriladi. Shunday qilib mualliflik korpusi keng imkoniyatli qidiruv tizimiga ega bo‘lib, muallif ijod qilgan barcha tur va janrdagi asarlar qamrab olinadigan, maxsus parametrlar asosida ham qidiruv imkoniyatiga ega, hajmi chegaralanmagan, muallif va uning ijodi bilan bog‘liq manbalarni qulay va tezkor olish mumkin bo‘lgan elektron ma’lumotlar bazasi hisoblanadi.'
    },
    {
        id: 10,
        title: 'Til korpusi va lingvistika',
        description: 'Korpus (lotincha “tana” demakdir) elektron holda saqlanadigan til birliklari majmuasi bo‘lib, tilshunoslar uchun turli muammolarni hal etish manbasi, foydalanuvchilar uchun esa lingvodidaktik va ta’limiy ahamiyatga ega tizimdir. Korpus tilshunosligi kompyuter lingvistikasi zamirida shakllangan soha bo‘lib, uning obyekti tabiiy tildagi matnlar, predmeti esa til korpuslari hisoblanadi. Muayyan tilning deyarli barcha tipdagi matnlari bazasidan iborat, turli maqsadlar doirasida lingvistik izohlari bilan qayta ishlangan korpus turi Milliy til korpusi, muayyan maqsadga mo‘ljallangan maxsus korpuslar esa uning xususiy / tarkibiy turi hisoblanadi. Jumladan, aksentologik korpus, parallel korpus, mualliflik korpusi, gazetalar korpusi, ta’limiy korpus, badiiy matnlar korpusi va h.k.\n' +
            '\n' +
            'Mualliflik korpusi muayyan bir muallif qalamiga mansub matnlar majmuasidan iborat tizim bo‘lib, asosan, yozuvchining yozish uslubi, asarlaridagi til, matn xususiyatlarini axborot texnologiyalari yordamida semantik tasniflab, tadqiq etishga asoslangan elektron shakdagi ma’lumotlar bazasi sanaladi. Mualliflik korpusining boshqa korpuslardan farqi uning bazasida muayyan bir muallif asarlari jamlanadi, matnlar qayta ishlanadi, grammatik va semantik teglanadi, qidiruv tizimi orqali muallifga tegishli materiallardan zaruriy ma’lumotlar, lingvistik ifodalar aniqlanadi, matnlar asosida statistik ma’lumotlar taqdim etiladi, metama’lumotlar aniq beriladi. Shunday qilib mualliflik korpusi keng imkoniyatli qidiruv tizimiga ega bo‘lib, muallif ijod qilgan barcha tur va janrdagi asarlar qamrab olinadigan, maxsus parametrlar asosida ham qidiruv imkoniyatiga ega, hajmi chegaralanmagan, muallif va uning ijodi bilan bog‘liq manbalarni qulay va tezkor olish mumkin bo‘lgan elektron ma’lumotlar bazasi hisoblanadi.'
    },
    {
        id: 11,
        title: 'Korpus va tarjima',
        description: 'Til korpuslarining tarjima amaliyotidagi o‘rni.'
    },
    {
        id: 12,
        title: 'Korpus va o‘quv jarayoni',
        description: 'Til o‘rganish jarayonida korpuslardan foydalanish.'
    },
    {
        id: 13,
        title: 'Til korpuslari va grammatika',
        description: 'Grammatika qoidalarini o‘rganishda til korpuslarining roli.'
    },
    {
        id: 14,
        title: 'Til korpuslari va leksikografiya',
        description: 'Leksikografiya sohasida til korpuslaridan foydalanish tajribalari.'
    }
];

export default korpus_mock_data;
